### ISSUE TITLE
What is this application exactly ?!!

### ISSUE THREAD

**Issue by Nokia808** [jkotra/eOVPN#1]
Hi.

Kindly, it is not clear - in read me - what this application exactly !! Can you address the following:

1) is it just other front end for well known command line tool "Openvpn" ?

2) if answer to question (1) above is yes, then by what it differ from "Connection Manager" say of GNOME or other DE ?? We have already GUI for Openvpn represented in "Connection Manager" .....

3) does your application has "VPN kill switch" option that configure itself AUTOMATICALLY if enabled ? If yes, then it is very worthy to try your application ..... Currently we need to add custom script & add an option in VPN configuration file to run this script (something need expert user: it took from me weeks to learn how to do it perfectly ......

4) does your application has GUI to edit (& or add) options within VPN configuration files, like:
- use TCP or UDP or BOTH 
- change the port
- enable port forwarding

In this case (point 4) it should show within it's GUI the default values .......

5) other point, which is very important: flatpak NEVER allow application that need ROOT permission. But open VPN need ROOT permission to rout ALL Internet traffic of PC/laptop within VPN ....... So, how flatpak package of your application do that without root permission ?!! 

All these should be explained in read me ........

Best

**Comment by jkotra** [comment]
1. Yes
2. most VPN providers don't provide a client for Linux instead they just give you a .zip file with thousands of configurations. each configuration need to be added manually to Network Manager, with no guarantee that it will work tomorrow (servers get added, deleted and throttled all the time depending on company policy and SOP). Adding and deleting VPN connection to system is cumbersome.
3. No, may be in future (subject to deliberation)
4. No, may be in future (subject to deliberation)
5. [flatpak-spawn](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-spawn)

a rewrite of `README.md` is planned which should rclear any ambiguity even to a novice user.

**Comment by Nokia808** [comment]
Okay, I see know. I will open "feature requests" for future development .....

Thank you.
