### ISSUE TITLE
eovpn simply does not work anymore

### ISSUE THREAD

**Issue by lbaiao** [jkotra/eOVPN#17]
Hi, I upgraded my system recently and eovpn stoped working. It won't even open anymore. Next, you can see my system's config:

OS: Garuda Linux x86_64
Host: A520 AORUS ELITE
Kernel: 5.13.10-zen1-1-zen
Uptime: 23 mins
Packages: 2162 (pacman)
Shell: bash 5.1.8
Resolution: 1920x1080
DE: qtile
WM: LG3D
Theme: Adwaita-dark [GTK2/3]
Icons: breeze-dark [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 7 5800X (16) @ 3.800GHz
GPU: AMD ATI Radeon 540/540X/550/550X / RX 540X/550/550X
Memory: 5033MiB / 32047MiB

aur/eovpn 0.41-1 (+1 0.16) (Installed)
    Application to connect, manage and update OpenVPN configurations

**Comment by jkotra** [comment]
Did you try to reset (from settings) and configuring it again? 

[Run the program in debug mode](https://github.com/jkotra/eOVPN#debug) and try to reproduce error. Paste the console output here.

**Comment by jkotra** [comment]
if it's not even opening, the problem should be pretty clear by simply running `eovpn` from console/terminal.

**Comment by jkotra** [comment]
Since you are using AUR version, just type `eovpn` in terminal. It will show you the reason why it's failing to launch.

**Comment by lbaiao** [comment]
Hi @jkotra. I did not try running it in debug mode. When I try to run it in the terminal, I get the following message:

bash: /usr/bin/eovpn: cannot execute binary file: Exec format error

**Comment by jkotra** [comment]
try uninstalling and installing it again.

also try [flatpak version](https://flathub.org/apps/details/com.github.jkotra.eovpn).
