### ISSUE TITLE
eOVPN (Linux elementary) issue "connecting"

### ISSUE THREAD

**Issue by jrabbott34** [jkotra/eOVPN#18]
It seems I'm having issue with eOVPN connecting after adding more client profiles.  I have uninstalled and re-installed, but still having issues.  It seems to pull back in the config from the former install. The issue is that I click "connect" and it just stays in a "connecting" status.  It never errors out, it just says connecting forever.  

Question:  How can I clear all pieces of eOVPN after uninstalling from AppCenter in elementary OS?  /var/...  ?

I'd like to just "gut it" and reinstall, but it seems to keep the old config

**Comment by jkotra** [comment]
is openvpn NetworkManager plugin installed?

`sudo apt-get install network-manager-openvpn`

**Comment by jkotra** [comment]
if you installed it through flatpak.

`flatpak remove eovpn --delete-data`

should take care of it.

**Comment by jrabbott34** [comment]
Thanks for the feedback!  Incidentally, it looks like there is an app
update, which is allowing me to load new configs.
