### ISSUE TITLE
[Feature Request] Provide visual feedback if wrong config file type supplied

### ISSUE THREAD

**Issue by gruentee** [jkotra/eOVPN#25]
Hi, 

thanks for making eOVPN, it looks slick.

I'd like to suggest the following usability improvement. A.t.m. it isn't totally obvious why a configuration file isn't accepted if it is not a ZIP file. If fed with a normal text file (OpenVPN configuration file) there should be some visual feedback showing an error. 
BTW is there any particular reason plain text files are not allowed?

**Comment by jkotra** [comment]
added a `MessageDialog` in `1.12` to show error if `Configuration Source` is not a `ZIP` file.

**Comment by gruentee** [comment]
Thanks, much appreciated!
