### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by altmash5** [jkotra/eOVPN#27]
So i am a new linux user i have setup a OpenVPN on aws and now i am using this tool to connect to it using this software but i am very confused that wha to ut on configuration source for openvpn and also i have configuration file with extension .ovpn and i dont know how to include it in configuratio 
if you can then please let me know the steps and destianation

PS- I am using pop os 21.04

**Comment by jkotra** [comment]
zip the file and put it somewhere (say `home`)

use `~/client.zip` as `Configuration Source` in settings.
where `~` refers to your home directory and `client.zip` is a zip file containing your `.ovpn` config file.

**Comment by altmash5** [comment]
thank you for your help
using this instruction i was able to add my connection to the list

But now when i click connect nothing happens 
i tried resetting it, i double checked the password but still nothing happens after clicking connect

**Comment by jkotra** [comment]
Make sure OpenVPN plugin for NM is installed:
```
sudo apt install network-manager-openvpn
sudo apt install network-manager-openvpn-gnome
```

**Comment by alexcocinda** [comment]
Hi, I have the same issue. After I installed the two APT packages, it is still not working.

**Comment by altmash5** [comment]
> Make sure OpenVPN plugin for NM is installed:
> 
> ```
> sudo apt install network-manager-openvpn
> sudo apt install network-manager-openvpn-gnome
> ```

I am really sorry for late reply 
but thank you very much fir your help 
installing plugins fixed the issue and everything is working fine
thank you very much for the help

**Comment by jkotra** [comment]
in `1.13`, flatpak users will shown warning message if openvpn plugin is not installed.
