### ISSUE TITLE
Servers search and ip check

### ISSUE THREAD

**Issue by ww-9** [jkotra/eOVPN#35]
The server search feature is absolutely necessary since there are often a lot of servers.

Also, when vpn killswitch is used at start of the application it can't get an ip and therefore it is in a constant spinning at the top and sometimes even hangs. We need either an option to control this behavior or just better handle situations where there is no internet access.

**Comment by ww-9** [comment]
By "constant spinning" I mean current ip display, not a situation where it can't connect to a VPN

**Comment by jkotra** [comment]
> The server search feature is absolutely necessary since there are often a lot of servers.

api bindings required to implement search were broken last time i checked. I will look into it sometime later.


> application it can't get an ip

IP resolution needs access to internet. in case of failure, it will fall back to placeholder UN flag and 0.0.0.0 as ip address.
![Screenshot from 2022-08-13 02-46-05](https://user-images.githubusercontent.com/29590316/184446118-e62bf52c-ecde-4ea8-8018-8107e5bdb5d6.png)

If you easily guess the problem by looking at debug logs: use `--debug DEBUG` arguments to enable debug logs.
