### ISSUE TITLE
[Feature request] Add "File Details" section.

### ISSUE THREAD

**Issue by Nokia808** [jkotra/eOVPN#7]
User should be able to view the contents of each VPN configuration file ..........

For that I suggest on you to add "Show Details" (or just "Details") option, so that by using it the user will see the contents of selected VPN configuration file .......

**Comment by jkotra** [comment]
thoughts on #3 and #7:

enabling user to edit config should be easy but it's not much of use without persistence. mechanism should be created/integrated in such a way that user edits are resistant to `update` (which at this point, deletes old folder and replaces with new one). 

will think on this, thanks for suggestion @Nokia808

**Comment by Nokia808** [comment]
@jkotra 
Dear, after re-thinking more than 3 times (not one time) I reached to the following: we need only to view file contents. Going beyond this into original request that I'm already closed #3 will take from your time too much for nothing because practically will convert your application into a file editor. We need your time for other useful features that if you add them will really create a great program providing a great help for Linux community .........

User - if need to edit a file - can simply download it then open it in text editor then add or change what she/he like, then import it (your application already support importing files from local storage.

**Comment by jkotra** [comment]
implemented in [0.07](https://github.com/jkotra/eOVPN/releases/tag/0.07)
