### ISSUE TITLE
[Feature request] Re-design the "Configuration Source" UI.

### ISSUE THREAD

**Issue by Nokia808** [jkotra/eOVPN#9]
Hi. I found that to use local .zip file (already downloaded .zip), user need to enter the path instead URL address. For the 1st time, I did not how to do this ! My mind think that this was a bug in flatpak version (you forgot some code ....). But after that I visit this repository & searched & founded in the "read me" the correct way for doing that. User should enter the path manually within the field instead of URL, like:
home/myusername/path-to/configs.zip

So, as you can see, the current state is confusing ! I have the following ideas to fix this. I will start from simple to more complex:

1) 1st fix to this - & simplest - is to replace the current shadow text that existing within the "Configuration Source" field by the following:
either "https://example.com/configs.zip" or "local-path-to/configs/zip"
You can abbreviate the above to only:
https://example.com/configs.zip or local-path/configs.zip

2) set a note just bellow the "Configuration Source" field saying:
either "https://example.com/configs.zip" or local-path-to/configs.zip
If you accept point (2) solution, then no need for shadow text within this field further.

3) make 2 fields for "Configuration Source" one bellow other:
1st one for "from URL" (should contain current shadow text "https://example.com/configs.zip")
2nd (bellow) for "from local path" (should be designed similar to that currently available for "OpenVPN CAR" field: by default show "NONE" & behave in same way of use file manager for selection)
Beside (before) each of these 2 fields a check box. User should select one of them by checking it's checkbox. When she/he do this, the other field should be inactive.
If User check 2nd choice (local path), then it should behave same way of the filed for "OpenVPN CAR"
If you accept solution (3), then "Validate" should be only offered for "from URL" field, so that it will be something like the following:

Configuration Source:
[ ] from URL ====================   Validate
[ ] from local path ================

Certainly solution (3) is more elegant, but it may take time & efforts from you ...........

**Comment by Nokia808** [comment]
I update my suggestion regarding solution (3), & to avoid confusing from text that may reached you via email notification I will set it bellow as following:

   If you accept solution (3), then "Validate" should be only offered for "from URL" field, so that it will be something like the following:

Configuration Source:
[ ] from URL ==================== Validate
[ ] from local path ================

**Comment by jkotra** [comment]
Addressed in [0.23](https://github.com/jkotra/eOVPN/releases/tag/0.23) 

Feedback appreciated.

**Comment by Nokia808** [comment]
@jkotra 
It seem very good re-design !

However, regarding "Validate" I can not say any thing, since I'm not using VPN. All my comments, issues that I'm posting are for the good of community because I see so many peoples like VPN.

Since there is already an opened issue for "Validate", I will close this issue.

**Comment by Nokia808** [comment]
Just a minutes ! I tested "Validate" & discover that no thing changed or improved regarding it. I will give my comment in it's issue not here ......
